apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9vcmVvOm5lZ3JvbmF1dGFAYXV0aGVudGljYXRpb24ubnBwajJvLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1BdXRoZW50aWNhdGlvbg==

