apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us-south1-docker.pkg.dev/micro-chiller-458819-r4/oreo-repository/auth:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-config
          env:
            - name : MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGO_URI
